# Generated by Django 3.0.2 on 2020-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='salary',
            field=models.FloatField(blank=True, default=0.0, max_length=100, verbose_name='salary'),
        ),
    ]
