# Generated by Django 3.0.2 on 2020-01-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_myuser_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='myuser',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
