# Generated by Django 3.0.2 on 2020-01-15 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200114_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='friend',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='dob',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
