# Generated by Django 3.0.2 on 2020-01-16 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20200115_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='friend',
            field=models.ManyToManyField(blank=None, default=None, null=True, related_name='friend_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
