# Generated by Django 3.0.2 on 2020-01-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_remove_myuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='users',
            new_name='friend',
        ),
    ]
