# Generated by Django 3.0.2 on 2020-01-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20200116_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='users',
        ),
    ]
