# Generated by Django 3.0.2 on 2020-01-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_auto_20200117_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
