# Generated by Django 3.0.2 on 2020-01-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20200117_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='users',
            new_name='friend',
        ),
    ]
