# Generated by Django 3.0.2 on 2020-01-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_auto_20200117_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request',
            field=models.BooleanField(blank=True, choices=[('APPROVED', 'approve'), ('NON_APPROVED', 'non_approve')], null=True),
        ),
    ]
