# Generated by Django 3.0.2 on 2020-01-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_auto_20200117_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request',
            field=models.BooleanField(blank=True, choices=[('approve', 'APPROVED'), ('NON_APPROVED', 'non_approve')], null=True),
        ),
    ]
