# Generated by Django 3.0.2 on 2020-01-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_auto_20200117_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request',
            field=models.CharField(blank=True, choices=[('A', 'APPROVED'), ('R', 'REJECTED')], max_length=1, null=True),
        ),
    ]
