# Generated by Django 3.0.2 on 2020-01-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_auto_20200117_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
