# Generated by Django 3.0.2 on 2020-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0021_auto_20200117_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='request',
        ),
        migrations.AddField(
            model_name='friend',
            name='reject',
            field=models.BooleanField(default=False, verbose_name='accept'),
        ),
    ]
