# Generated by Django 3.0.2 on 2020-01-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0022_auto_20200117_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='reject',
            new_name='request',
        ),
    ]
