# Generated by Django 3.0.2 on 2020-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0023_auto_20200117_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='request',
        ),
        migrations.AddField(
            model_name='friend',
            name='request_status',
            field=models.CharField(choices=[('APPROVE', 'APPROVE'), ('REJECT', 'REJECT'), ('PENDING', 'PENDING')], default='PENDING', max_length=50),
        ),
    ]
