# Generated by Django 3.0.2 on 2020-01-17 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0024_auto_20200117_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='friend',
            field=models.ManyToManyField(blank=None, default=None, null=True, related_name='friend_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
