# Generated by Django 3.0.2 on 2020-01-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0028_auto_20200120_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request_status',
            field=models.CharField(choices=[('APPROVE', 'APPROVE'), ('REJECT', 'REJECT'), ('PENDING', 'PENDING')], default='PENDING', max_length=20),
        ),
    ]
