# Generated by Django 3.0.2 on 2020-01-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0029_auto_20200120_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
