# Generated by Django 3.0.2 on 2020-01-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0031_auto_20200121_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
