# Generated by Django 3.0.2 on 2020-01-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0033_auto_20200121_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
