# Generated by Django 3.0.2 on 2020-01-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0036_auto_20200121_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
