# Generated by Django 3.0.2 on 2020-01-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0038_auto_20200121_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
    ]
